package Vista;

import Modelo.Usuario;
import Modelo.UsuarioDAO;
import java.awt.Color;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        panelUnderLogin = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        labelUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        cbRemerberme = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        labelAvatar = new javax.swing.JLabel();
        labelCardHeader = new javax.swing.JLabel();
        labelImagenUnion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir.setText("   X");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 40, 30));

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUnderLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelUnderLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelUnderLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUserName.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        labelUserName.setText("Usuario");
        panelLogin.add(labelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 40));

        txtUserName.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelLogin.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, -1));

        labelPassword.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        labelPassword.setText("Contraseña");
        panelLogin.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));

        txtPassword.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, -1));

        cbRemerberme.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        cbRemerberme.setText("Recuerdame");
        cbRemerberme.setBorder(null);
        panelLogin.add(cbRemerberme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        btnLogin.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnLogin.setText("Iniciar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 270, -1));

        panelUnderLogin.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 320, 220));

        labelAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Avatar_Container.png"))); // NOI18N
        panelUnderLogin.add(labelAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 80));

        labelCardHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Card_Header.png"))); // NOI18N
        panelUnderLogin.add(labelCardHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 90));

        bg.add(panelUnderLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 340, 370));

        labelImagenUnion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Union.png"))); // NOI18N
        bg.add(labelImagenUnion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 430));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        UsuarioDAO dao = new UsuarioDAO();
        Usuario user = new Usuario();
        
        if (!txtUserName.getText().equals("") && !txtPassword.getText().equals("")) {
            user.setUser((txtUserName.getText()));
            user.setPassword(txtPassword.getText());
            
            if (dao.login(user)) {
                this.dispose();
                Menu frm = new Menu();
                frm.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Los datos ingresados son incorrectos");
            }
        
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese los datos necesarios");
        } 
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setForeground(Color.red);
    }//GEN-LAST:event_btnSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Login().setVisible(true);
                
                Login log = new Login();
                log.setVisible(true);
                log.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnLogin;
    public javax.swing.JLabel btnSalir;
    private javax.swing.JCheckBox cbRemerberme;
    private javax.swing.JLabel labelAvatar;
    private javax.swing.JLabel labelCardHeader;
    private javax.swing.JLabel labelImagenUnion;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelUnderLogin;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
