package Vista;

import java.awt.Color;


public class NuevoUsuario extends javax.swing.JFrame {

    
    public NuevoUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNewUser = new javax.swing.JPanel();
        btnSalir = new javax.swing.JLabel();
        panelInsertNewUser = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnAddNewUser = new javax.swing.JButton();
        labelUserBackground = new javax.swing.JLabel();
        labelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNewUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir.setText("  X");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        panelNewUser.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 0, 30, 30));

        panelInsertNewUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        labelTitulo.setText("Agregar un nuevo usuario");
        panelInsertNewUser.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 200, 40));

        labelName.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        labelName.setText("Nombre ");
        panelInsertNewUser.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        labelLastName.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        labelLastName.setText("Apellidos");
        panelInsertNewUser.add(labelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        labelPassword.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        labelPassword.setText("Contraseña");
        panelInsertNewUser.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        panelInsertNewUser.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 160, -1));
        panelInsertNewUser.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 160, -1));

        labelUser.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        labelUser.setText("Usuario");
        panelInsertNewUser.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        panelInsertNewUser.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 160, -1));
        panelInsertNewUser.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, -1));

        btnAddNewUser.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnAddNewUser.setText("AGREGAR USUARIO");
        panelInsertNewUser.add(btnAddNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 220, 60));

        labelUserBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Education.png"))); // NOI18N
        panelInsertNewUser.add(labelUserBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 240));

        panelNewUser.add(panelInsertNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 660, 240));

        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ulatina Online.png"))); // NOI18N
        panelNewUser.add(labelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 380));

        getContentPane().add(panelNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setForeground(Color.white);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setForeground(Color.red);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddNewUser;
    public javax.swing.JLabel btnSalir;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUserBackground;
    private javax.swing.JPanel panelInsertNewUser;
    private javax.swing.JPanel panelNewUser;
    public javax.swing.JTextField txtLastName;
    public javax.swing.JTextField txtName;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
